"""Add user profile fields

Revision ID: 858065e5aae4
Revises: 
Create Date: 2024-12-07 14:44:49.266769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858065e5aae4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('default_view', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('default_priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('due_date_reminder', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('project_updates', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('task_assignments', sa.Boolean(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('task_assignments')
        batch_op.drop_column('project_updates')
        batch_op.drop_column('due_date_reminder')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('default_priority')
        batch_op.drop_column('theme')
        batch_op.drop_column('default_view')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
